language: julia
os:
  - linux
julia:
  - 0.5
  - 0.6
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("SparseGrids"); Pkg.test("SparseGrids"; coverage=true)'
after_success:
   - julia -e 'cd(Pkg.dir("SparseGrids")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
